### ISSUE TITLE
exitステータスの確認

### ISSUE THREAD

**Issue by arMaNi843739** [sniper-fly/minishell#120]
exitステータスがおかしいケースがあったのでメモしておきます
```
minishell> ./minishell
minishell > exit 1
exit
minishell> echo $?
256
```

**Comment by sniper-fly** [comment]
minishellの中でminishell起動は不具合が起きやすいですし、かなり複雑になってしまうので、禁止してしまった方がいいかもしれません。

**Comment by arMaNi843739** [comment]
禁止というのが許されるんですかね笑
レビュー項目に載ってたら大丈夫だとは思いますが，bashではだいじょうぶなんだから実装しないとだめじゃね？派閥も出てくる気もします．
でも自分でこんなこと言っておいて実装できるかどうかもわからないので，一応保留にしておきます．

**Comment by sniper-fly** [comment]
レビュー項目に禁止してもよいかどうか載っていたら大丈夫かということでしょうか？
レビュー項目にminishell内でminishellを起動する検査項目が存在していたら対応すべきですが、
やらなくてもいいことまでは基本的には書かれてないですよね。
現時点でもsyntax errorのメッセージに関しては自分で定義しているので、
minishellもbashを参考にしろとは言うもののある程度の動作の自由はあってよいと思ってます。

ちなみに、minishell内でminishellを起動すると、一見普通のコマンドの実行は問題ないように見えますが、
シグナルの挙動がおかしくなります。これに対して対応する方法は、、、わかりません。

**Comment by arMaNi843739** [comment]
ではminishell内でminishellを呼んだ時の挙動は未定義という方向で押しましょう．
