### ISSUE TITLE
minishell自体の終了ステータスが反映されない

### ISSUE THREAD

**Issue by sniper-fly** [sniper-fly/minishell#122]
minishell自体の終了ステータスが、常に0で返ってきているようです。

**Comment by arMaNi843739** [comment]
exit(g_status)と書いてないところが残っているからだと思います．
調査しておきます．

**Comment by sniper-fly** [comment]
exit() 関数は、プロセスを正常に終了させ、 status & 0377 という値を親プロセスへ返す (wait(2) を参照)。
https://linuxjm.osdn.jp/html/LDP_man-pages/man3/exit.3.html

**Comment by sniper-fly** [comment]
status & 0377 を出力すると 0になってしまいました。

**Comment by sniper-fly** [comment]
0377を2進数に変換すると
101111001
こうなります。
つまり、exitでは
~~2を親プロセスにリターンすることができないようです。~~
~~returnを使う方法でプロセスの終了をしないといけないようです。~~
exit(2)としたら親プロセスに2を伝えられました。。よくわかりません。

**Comment by arMaNi843739** [comment]
0377ってたぶん8進数表記なので2進数変換したら11111111ですね
だからstatusに256以上の数字が来ても終了ステータスは0-255の範囲内になるんだと思います(というより0-255の範囲になるように0377(255)で&を取ってるんだと思います)
