### ISSUE TITLE
リダイレクトのバグ

### ISSUE THREAD

**Issue by arMaNi843739** [sniper-fly/minishell#127]
リダイレクトのテストで起こったバグを載せておきます
ただコマンド実行上のバグの可能性もあるので，あまり深く探しすぎなくても大丈夫です．

**Comment by arMaNi843739** [comment]
```
ls < noexist 2> ./test/var_parse/execute10
```

**Comment by arMaNi843739** [comment]
```
export foo='        space       ' ; echo space >$foo ; ls
```
このコマンドでリダイレクト先のファイル名が"        space       "となりました．パースの確認お願いします

**Comment by sniper-fly** [comment]
・空白をスキップして、リダイレクトファイル名取得（環境変数含む）
・環境変数展開
・クォートの除去

という順番でやってたので、環境変数展開後にスペースがあったときに除去できてなかったのが原因でした。
strtrimを一回噛ませれば治るかなと思います。発見ありがとうございます！
