### ISSUE TITLE
ファイルやディレクトリを扱うビルトイン関数のバグ

### ISSUE THREAD

**Issue by arMaNi843739** [sniper-fly/minishell#130]

**Comment by arMaNi843739** [comment]
bashの実行結果 :
```
>mkdir test_pwd
>cd test_pwd
> rmdir ../test_pwd
>pwd
<path>/test_pwd
>cd .
cd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
>pwd
<path>/test_pwd/.
```
~~このことから，pwdは環境変数のPWDを出力してるだけだということがわかりました．~~
環境変数PWDがunsetされた場合でもpwdは動いているので，PWDがあればそっちを出力，なければgetcwdを用いて出力，という形になるのかと思いました
(自分の実装ではgetcwdでパスを取得して出力していました)

**Comment by arMaNi843739** [comment]
```
>mkdir test_pwd
>cd test_pwd
>rmdir ../test_pwd
>pwd
<path>/test_pwd
>unset PWD
>pwd
<path>/test_pwd
```
unsetする前とした後で同じ出力結果という謎挙動...
もちろんgetcwdしても動くはずがないので意味わからなすぎます

**Comment by sniper-fly** [comment]
> bashの実行結果 :
> 
> ```
> >mkdir test_pwd
> >cd test_pwd
> > rmdir ../test_pwd
> >pwd
> <path>/test_pwd
> >cd .
> cd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> >pwd
> <path>/test_pwd/.
> ```
> 
> ~このことから，pwdは環境変数のPWDを出力してるだけだということがわかりました．~
> 環境変数PWDがunsetされた場合でもpwdは動いているので，PWDがあればそっちを出力，なければgetcwdを用いて出力，という形になるのかと思いました
> (自分の実装ではgetcwdでパスを取得して出力していました)

PWDがあればそちらを入力するということでいいと思います。
謎挙動過ぎるので、なければgetcwdを用いて出力という妥協点でいいと思います。
