### ISSUE TITLE
PATHの検索対象のディレクトリの名前に：が含まれていたら？

### ISSUE THREAD

**Issue by sniper-fly** [sniper-fly/minishell#23]
https://github.com/sniper-fly/minishell/issues/22

**Comment by sniper-fly** [comment]
調べました。

unset PATH
によりPATHを削除

hello
とだけ出力する実行ファイル（puthello）を
/home/rnakai/labo/minishell_case/a:b,

goodbyeとだけ出力する実行ファイル（saygoodbye）を
/home/rnakai/labo/minishell_case/a

に配置しました。

それから、export PATH="/home/rnakai/labo/minishell_case/a:b"
としてPATHを再設定しました。

それからexportで表示すると
declare -x PATH="/home/rnakai/labo/minishell_case/a:b"
このようになりました。

/home/rnakai/labo/minishell_case/a
に置いているsaygoodbyeコマンドは起動できましたが、

/home/rnakai/labo/minishell_case/a:b
においてあるputhelloコマンドは実行できませんでした。

よって、環境変数は素直に：を含めて設定され、特にディレクトリ名と区別することもないので、
素直にsplitで分けて解釈するということで問題ないと思います。

**Comment by arMaNi843739** [comment]
調べていただきありがとうございました．:でsplitする方向で実装してみます
