### ISSUE TITLE
【ビルトイン関数】cd

### ISSUE THREAD

**Issue by sniper-fly** [sniper-fly/minishell#25]

**Comment by sniper-fly** [comment]
cdコマンドを実行すると、環境変数PWD, OLDPWDを書き換えるようです。

**Comment by arMaNi843739** [comment]
```cd #```でホームディレクトリに移動
ただし，
```cd #/<ホームディレクトリ以下のディレクトリ>```を実行してもホームディレクトリへ移動

**Comment by arMaNi843739** [comment]
```cd (引数無し)```でホームディレクトリに移動
