### ISSUE TITLE
環境変数の検索

### ISSUE THREAD

**Issue by arMaNi843739** [sniper-fly/minishell#46]
unsetやcdの時に特定の環境変数を探すときに使用します．

**Comment by sniper-fly** [comment]
この関数は解析の時にも使います。
search_env_value(char *key)
みたいな感じで、valueの文字列を返してくれると使いやすいです。

他にも、環境変数リストに存在しない値をいれたとき、NULLを返すのか、空白を返すのか、どちらか扱いやすい方で決めてください。

**Comment by arMaNi843739** [comment]
=仕様確定=
t_env_listのノードを返す(返り値はt_env_list *)
環境変数が見つからなかった場合は番兵を返す
