### ISSUE TITLE
2/1 ~ 2/7の予定

### ISSUE THREAD

**Issue by sniper-fly** [sniper-fly/minishell#47]

**Comment by sniper-fly** [comment]
- [x] 文字列解析関数（特殊文字以外、；｜の分割）至急！

- [x] read_cmd_lineの完成

- [x] 環境変数をヘッダで定義しないようにリファクタリング

- [ ] シグナルの設定

**Comment by arMaNi843739** [comment]
- [x] exec_cmdの実装(リストの前後が番兵かどうかの確認をする)
- [x] my_execveを動かせるようにする
- [x]  statusをexternグローバル変数として宣言する
- [x] シグナル処理のために最後に実行されたコマンドのpidを保存
- [x] エラー時のstatusを保存
- [ ] built-in関数の実装
- [ ] 環境変数を検索する関数を実装
- [x] ビルトインとenvのヘッダー(1ディレクトリ1ヘッダー)
- [x] 環境変数リストのグローバル変数をヘッダーではなく各ソースファイルの頭に書く

```
waitpid(); // 最後のプロセスのstatusを取得
for(プロセスの数) wait(NULL);
exit(最後のプロセスのstatus);
```
