### ISSUE TITLE
readした値のvalidation(syntax error検査)

### ISSUE THREAD

**Issue by sniper-fly** [sniper-fly/minishell#56]
https://github.com/sniper-fly/minishell/wiki/syntax-error%E3%81%BE%E3%81%A8%E3%82%81%EF%BC%88from-syamashi%EF%BC%89

**Comment by sniper-fly** [comment]
検査項目

・ascii文字列範囲内かどうか
・", ' がちゃんとセットで存在しているか
・\ で終端していないか

**Comment by arMaNi843739** [comment]
bashのエラーそのまま再現しなくてもいい
ex) クォートが閉じてない，程度に書いておけばいい

read_cmd_lineの後に検査する(引数はline)

**Comment by arMaNi843739** [comment]
invalid
```
echo '
echo "
echo "'
echo '"
echo ""'
echo "''
```

valid
```
> echo "''"
''
> echo "'"'"'
 '"
> echo "h'e"l'l"o'
h'ell"o
```

**Comment by sniper-fly** [comment]
これは
"h'e" と l  と  'l"o'  がくっついたものだと考えるとわかりやすいです。
クォートが連続した場合、一つのつながった文字列だと考えます
（つながった文字列かどうか考えるのは解析の仕事なので、あくまでシンタックスエラーになる場合をはじくだけでいいです。）

**Comment by sniper-fly** [comment]
"a\\"a"
こういうのも閉じていると考えるので注意してください。
ただし、
'a\\'a'
これは閉じてません。

**Comment by sniper-fly** [comment]
あと、
<<
みたいなケースは本家はエラーになりませんが、今回は対応しないのでエラーにしてください。
